# Generated by Django 5.0.6 on 2024-05-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstapp',
            name='id',
        ),
        migrations.AddField(
            model_name='firstapp',
            name='auto_field',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
